In [1]:
import numpy as np 

In [5]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [13]:
d=[]
for i in h:
    d.append(i+5)

In [15]:
d

[35, 25, 10, 13, 14]

In [45]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [47]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
s=tuple(k)
k

[36, 4, 9, 81, 49, 25, 64]

In [49]:
s

(36, 4, 9, 81, 49, 25, 64)

In [51]:
m=[]
for i in s:
    if i>30:
        m.append(i)

In [53]:
m

[36, 81, 49, 64]

In [87]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])

In [89]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [91]:
arr*5

array([100, 250, 150, 350, 400, 200, 180, 270, 115, 490])

In [93]:
arr/2

array([10. , 25. , 15. , 35. , 40. , 20. , 18. , 27. , 11.5, 49. ])

In [95]:
arr**2

array([ 400, 2500,  900, 4900, 6400, 1600, 1296, 2916,  529, 9604])

In [97]:
arr>50

array([False, False, False,  True,  True, False, False,  True, False,
        True])

In [101]:
arr[arr>50]

array([70, 80, 54, 98])

In [112]:
arr[0]

20

In [114]:
k

[36, 4, 9, 81, 49, 25, 64]

In [120]:
np.where(arr>50)

(array([3, 4, 7, 9], dtype=int64),)