1)numpy         array operations
2)pandas         Data manipulation and analysis
3)matplotlib and Seaborn    Graphical  Analysis
4)sklearn        machine learning algorithms and techniques
5)statsmodels    statistical analysis
6)scipy          statistical analysis

In [2]:
import numpy as np

In [4]:
j=[5,7,2,8,4,7]
j

[5, 7, 2, 8, 4, 7]

In [10]:
d=np.array(j)
d

array([5, 7, 2, 8, 4, 7])

In [22]:
d

array([5, 7, 2, 8, 4, 7])

In [20]:
type(d)

numpy.ndarray

In [14]:
d.shape

(6,)

In [16]:
d.ndiml

1

In [18]:
d.size

6

In [38]:
k=([4,8,90.12],
   [56,78,54,20],
   [67,89,50,49],
   [77,88,22,55],
   [90,40,70,60])

In [44]:
m=[3,4,5,6,7,8,9,10,11,12]
m

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [48]:
list(range(3,13))

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [52]:
list(range(3,13,3))

[3, 6, 9, 12]

In [54]:
list(range(5,500))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 1

In [56]:
tuple(range(5,500))

(5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 1

In [58]:
tuple(range(5,506,100))

(5, 105, 205, 305, 405, 505)

In [60]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [64]:
range(-1,-10)

range(-1, -10)

In [72]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [74]:
list(range(10,-10,-2))

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [76]:
[2.5,3,3.5,4,4.5]

[2.5, 3, 3.5, 4, 4.5]

In [82]:
np.arange(2.5,5,5.0)

array([2.5])

In [84]:
np.arange(5,10,1)

array([5, 6, 7, 8, 9])

In [88]:
for i in range(5,50,5):
    print("Data" ,i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [92]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [106]:
range(len(j))

range(0, 11)

In [112]:
range(8)

range(0, 8)

In [94]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])

In [110]:
x,y 

([5, 23, 62, 80, 77, 80], [87, 46, 84, 45, 33])

In [108]:
for i in range(len(j)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
