In [17]:
import numpy as np

In [47]:
a=np.random.randint(30,99,(7,7))
a

array([[94, 77, 82, 85, 38, 91, 36],
       [51, 69, 35, 71, 90, 79, 97],
       [90, 49, 57, 65, 89, 61, 45],
       [38, 33, 88, 41, 74, 78, 50],
       [74, 32, 73, 70, 80, 31, 51],
       [61, 55, 44, 59, 90, 77, 93],
       [80, 98, 69, 41, 68, 98, 55]])

In [49]:
a.ndim

2

In [58]:
a.shape

(7, 7)

In [54]:
a[3]

array([38, 33, 88, 41, 74, 78, 50])

array[row_start: row_end: row_step,col_start:col_end:col_step1]

In [93]:
import pandas as pd

In [95]:
k=[4,7,2,9,7,3,90,50]
k

[4, 7, 2, 9, 7, 3, 90, 50]

In [97]:
np.array(k)

array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [99]:
pd.Series(k)

0     4
1     7
2     2
3     9
4     7
5     3
6    90
7    50
dtype: int64

In [101]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [103]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [105]:
t.ndim

2

In [107]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [ ]:
pd.DataFrame(t,colums=['name','sub']

In [1]:
df.columns

NameError: name 'df' is not defined

In [3]:
import pandas as pd
import seaborn as sns

In [5]:
sns.load_dataset('iris')

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [12]:
df=sns.load_dataset('taxis')
df

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
6428  1.06    0.0   6.36   green  credit card      East Harlem North   
6429  0.00    0.0  58.80   green  credit card                Jamaica   
6430  0.00    0.0  17.30   green         cash    Crown Heights North   
6431  0.00    0.0   6.80   green  credit card          East New York   
6432  3.36    0.0  20.16   green  credit card            Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 14 columns]

In [14]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.shape

(6433, 14)

In [18]:
df.columns

Index(['pickup', 'dropoff', 'passengers', 'distance', 'fare', 'tip', 'tolls',
       'total', 'color', 'payment', 'pickup_zone', 'dropoff_zone',
       'pickup_borough', 'dropoff_borough'],
      dtype='object')

In [20]:
df['color'].unique()

array(['yellow', 'green'], dtype=object)

In [22]:
df['color'].value_counts()

color
yellow    5451
green      982
Name: count, dtype: int64

In [24]:
df['payment'].unique()

array(['credit card', 'cash', nan], dtype=object)

In [26]:
df['payment'].value_counts()

payment
credit card    4577
cash           1812
Name: count, dtype: int64

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64         
 3   distance         6433 non-null   float64       
 4   fare             6433 non-null   float64       
 5   tip              6433 non-null   float64       
 6   tolls            6433 non-null   float64       
 7   total            6433 non-null   float64       
 8   color            6433 non-null   object        
 9   payment          6389 non-null   object        
 10  pickup_zone      6407 non-null   object        
 11  dropoff_zone     6388 non-null   object        
 12  pickup_borough   6407 non-null   object        
 13  dropoff_borough  6388 non-null   object        
dtypes: datetime64[ns](2), float64(5), int64(

In [30]:
a=pd.Series(['india','5',2,8.6,4,9])

In [32]:
a

0    india
1        5
2        2
3      8.6
4        4
5        9
dtype: object

In [34]:
df.iloc[1:11]

pickup             dropoff  passengers  distance  fare   tip  \
1  2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0  0.00   
2  2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5  2.36   
3  2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0  6.15   
4  2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0  1.10   
5  2019-03-11 10:37:23 2019-03-11 10:47:31           1      0.49   7.5  2.16   
6  2019-03-26 21:07:31 2019-03-26 21:17:29           1      3.65  13.0  2.00   
7  2019-03-22 12:47:13 2019-03-22 12:58:17           0      1.40   8.5  0.00   
8  2019-03-23 11:48:50 2019-03-23 12:06:14           1      3.63  15.0  1.00   
9  2019-03-08 16:18:37 2019-03-08 16:26:57           1      1.52   8.0  1.00   
10 2019-03-16 10:02:25 2019-03-16 10:22:29           1      3.90  17.0  0.00   

    tolls  total   color      payment                pickup_zone  \
1     0.0   9.30  yellow         cash      Upper West Side South   
2     0.0  14.16  yellow  credit card              Alphabet City   
3     0.0  36.95  yellow  credit card                  Hudson Sq   
4     0.0  13.40  yellow  credit card               Midtown East   
5     0.0  12.96  yellow  credit card  Times Sq/Theatre District   
6     0.0  18.80  yellow  credit card          Battery Park City   
7     0.0  11.80  yellow          NaN                Murray Hill   
8     0.0  19.30  yellow  credit card          East Harlem South   
9     0.0  13.30  yellow  credit card        Lincoln Square East   
10    0.0  17.80  yellow         cash          LaGuardia Airport   

               dropoff_zone pickup_borough dropoff_borough  
1     Upper West Side South      Manhattan       Manhattan  
2              West Village      Manhattan       Manhattan  
3            Yorkville West      Manhattan       Manhattan  
4            Yorkville West      Manhattan       Manhattan  
5              Midtown East      Manhattan       Manhattan  
6   Two Bridges/Seward Park      Manhattan       Manhattan  
7                  Flatiron      Manhattan       Manhattan  
8            Midtown Center      Manhattan       Manhattan  
9              Central Park      Manhattan       Manhattan  
10                  Astoria         Queens          Queens

In [36]:
df.iloc[1:10,1:10]

dropoff  passengers  distance  fare   tip  tolls  total   color  \
1 2019-03-04 16:19:00           1      0.79   5.0  0.00    0.0   9.30  yellow   
2 2019-03-27 18:00:25           1      1.37   7.5  2.36    0.0  14.16  yellow   
3 2019-03-10 01:49:51           1      7.70  27.0  6.15    0.0  36.95  yellow   
4 2019-03-30 13:37:14           3      2.16   9.0  1.10    0.0  13.40  yellow   
5 2019-03-11 10:47:31           1      0.49   7.5  2.16    0.0  12.96  yellow   
6 2019-03-26 21:17:29           1      3.65  13.0  2.00    0.0  18.80  yellow   
7 2019-03-22 12:58:17           0      1.40   8.5  0.00    0.0  11.80  yellow   
8 2019-03-23 12:06:14           1      3.63  15.0  1.00    0.0  19.30  yellow   
9 2019-03-08 16:26:57           1      1.52   8.0  1.00    0.0  13.30  yellow   

       payment  
1         cash  
2  credit card  
3  credit card  
4  credit card  
5  credit card  
6  credit card  
7          NaN  
8  credit card  
9  credit card

In [38]:
import numpy as np

In [40]:
a=np.random.randint(10,50,25)
a

array([36, 27, 19, 23, 14, 13, 26, 37, 37, 28, 17, 27, 12, 45, 39, 27, 13,
       29, 25, 26, 32, 43, 30, 37, 15])

In [42]:
df[df['payment']=='cash']

pickup             dropoff  passengers  distance  fare  tip  \
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0  0.0   
10   2019-03-16 10:02:25 2019-03-16 10:22:29           1      3.90  17.0  0.0   
13   2019-03-19 07:55:25 2019-03-19 08:09:17           1      1.75  10.5  0.0   
14   2019-03-27 12:13:34 2019-03-27 12:25:48           0      2.90  11.5  0.0   
15   2019-03-16 17:53:34 2019-03-16 18:13:57           3      2.09  13.5  0.0   
...                  ...                 ...         ...       ...   ...  ...   
6420 2019-03-16 15:39:23 2019-03-16 15:46:18           2      1.20   7.0  0.0   
6422 2019-03-22 20:17:35 2019-03-22 20:36:07           1      4.02  16.0  0.0   
6424 2019-03-30 20:52:15 2019-03-30 20:59:55           1      1.70   8.0  0.0   
6427 2019-03-23 18:26:09 2019-03-23 18:49:12           1      7.07  20.0  0.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0  0.0   

      tolls  total   color payment               pickup_zone  \
1       0.0    9.3  yellow    cash     Upper West Side South   
10      0.0   17.8  yellow    cash         LaGuardia Airport   
13      0.0   13.8  yellow    cash       Lincoln Square West   
14      0.0   14.8  yellow    cash  Financial District North   
15      0.0   16.8  yellow    cash     Upper West Side North   
...     ...    ...     ...     ...                       ...   
6420    0.0    7.8   green    cash            Central Harlem   
6422    0.0   17.3   green    cash  Washington Heights South   
6424    0.0    9.3   green    cash            Central Harlem   
6427    0.0   20.0   green    cash               Parkchester   
6430    0.0   17.3   green    cash       Crown Heights North   

                    dropoff_zone pickup_borough dropoff_borough  
1          Upper West Side South      Manhattan       Manhattan  
10                       Astoria         Queens          Queens  
13     Times Sq/Theatre District      Manhattan       Manhattan  
14       Two Bridges/Seward Park      Manhattan       Manhattan  
15                  Clinton East      Manhattan       Manhattan  
...                          ...            ...             ...  
6420       Upper West Side North      Manhattan       Manhattan  
6422  Spuyten Duyvil/Kingsbridge      Manhattan           Bronx  
6424        Central Harlem North      Manhattan       Manhattan  
6427           East Harlem South          Bronx       Manhattan  
6430              Bushwick North       Brooklyn        Brooklyn  

[1812 rows x 14 columns]

In [44]:
df[df['total']>=10]

pickup             dropoff  passengers  distance   fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.00   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.50   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.00   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.00   
5    2019-03-11 10:37:23 2019-03-11 10:47:31           1      0.49   7.50   
...                  ...                 ...         ...       ...    ...   
6425 2019-03-07 15:34:30 2019-03-07 16:31:06           1      9.12  26.32   
6427 2019-03-23 18:26:09 2019-03-23 18:49:12           1      7.07  20.00   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.00   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.00   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.00   

       tip  tolls  total   color      payment                pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card            Lenox Hill West   
2     2.36    0.0  14.16  yellow  credit card              Alphabet City   
3     6.15    0.0  36.95  yellow  credit card                  Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card               Midtown East   
5     2.16    0.0  12.96  yellow  credit card  Times Sq/Theatre District   
...    ...    ...    ...     ...          ...                        ...   
6425  0.00    0.0  26.82   green  credit card                 Park Slope   
6427  0.00    0.0  20.00   green         cash                Parkchester   
6429  0.00    0.0  58.80   green  credit card                    Jamaica   
6430  0.00    0.0  17.30   green         cash        Crown Heights North   
6432  3.36    0.0  20.16   green  credit card                Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
5                         Midtown East      Manhattan       Manhattan  
...                                ...            ...             ...  
6425                     East New York       Brooklyn        Brooklyn  
6427                 East Harlem South          Bronx       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[5190 rows x 14 columns]