1)numpy         array operations
2)pandas         Data manipulation and analysis
3)matplotlib and Seaborn    Graphical  Analysis
4)sklearn        machine learning algorithms and techniques
5)statsmodels    statistical analysis
6)scipy          statistical analysis

In [2]:
import numpy as np

In [4]:
j=[5,7,2,8,4,7]
j

[5, 7, 2, 8, 4, 7]

In [10]:
d=np.array(j)
d

array([5, 7, 2, 8, 4, 7])

In [22]:
d

array([5, 7, 2, 8, 4, 7])

In [20]:
type(d)

numpy.ndarray

In [14]:
d.shape

(6,)

In [16]:
d.ndiml

1

In [18]:
d.size

6

In [38]:
k=([4,8,90.12],
   [56,78,54,20],
   [67,89,50,49],
   [77,88,22,55],
   [90,40,70,60])

In [44]:
m=[3,4,5,6,7,8,9,10,11,12]
m

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [48]:
list(range(3,13))

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [52]:
list(range(3,13,3))

[3, 6, 9, 12]

In [54]:
list(range(5,500))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 1

In [56]:
tuple(range(5,500))

(5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 1

In [58]:
tuple(range(5,506,100))

(5, 105, 205, 305, 405, 505)

In [60]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [64]:
range(-1,-10)

range(-1, -10)

In [72]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [74]:
list(range(10,-10,-2))

[10, 8, 6, 4, 2, 0, -2, -4, -6, -8]

In [76]:
[2.5,3,3.5,4,4.5]

[2.5, 3, 3.5, 4, 4.5]

In [82]:
np.arange(2.5,5,5.0)

array([2.5])

In [84]:
np.arange(5,10,1)

array([5, 6, 7, 8, 9])

In [88]:
for i in range(5,50,5):
    print("Data" ,i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [92]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [106]:
range(len(j))

range(0, 11)

In [112]:
range(8)

range(0, 8)

In [94]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])

In [110]:
x,y 

([5, 23, 62, 80, 77, 80], [87, 46, 84, 45, 33])

In [108]:
for i in range(len(j)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [9]:
import numpy as np

In [11]:
d=np.array([10,40,50,30,70])
d

array([10, 40, 50, 30, 70])

In [13]:
np.mean(d)

40.0

In [15]:
np.median(d)

40.0

In [17]:
np.var(d)

400.0

In [19]:
np.std(d)

20.0

In [21]:
np.max(d)

70

In [23]:
np.min(d)

10

In [25]:
np.quantile(d,0.25)

30.0

Q1=np.quantile(d,0.25)  
Q2=np.quantile(d,0.5)
Q3=np.quantile(d,0.75)

In [28]:
r=np.random.rand(5,3)  # range is from 0 to 1 standard normmaly DATA
r

array([[0.70680955, 0.47471418, 0.98254029],
       [0.48538859, 0.31152469, 0.88133991],
       [0.0604432 , 0.90441681, 0.30860895],
       [0.2321196 , 0.40429405, 0.15694953],
       [0.75577885, 0.1817207 , 0.71086504]])

In [30]:
r.size

15

In [32]:
r.ndim

2

In [34]:
r.shape

(5, 3)

In [38]:
r=np.random.rand(5,3,2)
r

array([[[0.96686555, 0.25875775],
        [0.28722346, 0.13960434],
        [0.39148343, 0.0878673 ]],

       [[0.18157816, 0.0856234 ],
        [0.05873796, 0.8602764 ],
        [0.27299286, 0.03253348]],

       [[0.57534599, 0.84303321],
        [0.65683637, 0.4466727 ],
        [0.65273615, 0.74273361]],

       [[0.4836523 , 0.48987257],
        [0.78961411, 0.52141652],
        [0.50739699, 0.94208476]],

       [[0.32657033, 0.91016238],
        [0.93401473, 0.35680789],
        [0.24795074, 0.93754655]]])

In [46]:
r=np.random.randn(30,1)   #-3 to +3 standard normally DATA
r

array([[ 0.13886704],
       [ 0.01170587],
       [-0.98973854],
       [-0.75500993],
       [ 0.07230806],
       [-1.60635556],
       [-1.64562857],
       [ 0.83172365],
       [ 1.22662554],
       [-1.23267417],
       [-2.34646105],
       [ 0.02090497],
       [-2.08682713],
       [-0.83386267],
       [-1.51973508],
       [-1.67772563],
       [ 0.75795284],
       [ 2.41537787],
       [ 1.17561346],
       [-0.7481969 ],
       [-0.26912826],
       [ 0.30564282],
       [-1.8735924 ],
       [-2.63978157],
       [ 0.25825221],
       [-0.42030885],
       [-0.35981782],
       [-0.26374267],
       [-0.94127211],
       [ 1.46917367]])

In [52]:
np.random.normal(40,5)

43.06036250348343

In [54]:
np.random.normal(40,5,(5,4))  # (5,4) it is a shape and 40,5-40|5=20

array([[44.81295595, 41.39655318, 50.96592195, 44.07381995],
       [39.62392548, 36.18824302, 39.95634808, 43.78658513],
       [35.42146868, 40.19175455, 34.99959857, 39.87974255],
       [44.30326268, 33.91131406, 41.64661085, 36.88799017],
       [42.64876438, 36.71972575, 39.04721746, 34.13065802]])

In [165]:
np.random.randint(35,91)

90

In [169]:
np.random.randint(35,86,(5,5))

array([[76, 76, 83, 67, 54],
       [46, 55, 48, 74, 39],
       [35, 67, 62, 35, 42],
       [43, 46, 84, 44, 84],
       [46, 79, 80, 69, 74]])